### PR TITLE
Add rollout + analysisTemplate for express-microservice

### PR DESCRIPTION
**Pull request by TedSpinks**
Hi @jcantosz, I think this should be good to go. I left the deployment.yaml intact (but no longer referenced by base kustomization.yaml) in case you need to compare it to rollout.yaml for debugging.

### CODE REVIEW

**Comment by TedSpinks** [comment]
@jcantosz oops, I need to update the destination namespaces too...

**Comment by TedSpinks** [comment]
OK so _now_ I think it should be good to go ;-) Side note, I also enabling pruning on the apps so that the sync will cleanup the old deployment resources.

**Comment by jcantosz** [comment]
I am reverting the pruning changes. Those changes will cause the app to autosync. We have a pipeline that syncs the app, thus removing the `automated'` blocks

**Review by jcantosz — APPROVED** [review]
LGTM

**Pull request merged**
